import type { ComponentDef } from './types';

/**
 * Canonical component catalog.
 *
 * Numbers are intentionally simplified for gameplay clarity, not real-world
 * precision. Latency is the per-request cost added on the critical path;
 * availability is fractional (0.9999 = four 9s); cost is USD/month per unit.
 *
 * These power the simulation engine in @sd-game/game-engine.
 */
export const COMPONENTS: ComponentDef[] = [
  /* ---- Edge ---- */
  {
    id: 'cdn-cloudflare',
    type: 'cdn',
    name: 'CDN',
    icon: '🌍',
    category: 'edge',
    baseLatency: 5,
    capacity: 100_000,
    costPerMonth: 200,
    availability: 0.99999,
    failureRate: 0.00001,
    description: 'Serves static/cached assets from edge locations near users. Huge capacity, cheap, very reliable.',
    props: { cacheHitRatio: 0.9 },
  },
  {
    id: 'dns-route53',
    type: 'gateway',
    name: 'DNS',
    icon: '📖',
    category: 'edge',
    baseLatency: 20,
    capacity: 200_000,
    costPerMonth: 50,
    availability: 0.99999,
    failureRate: 0.00001,
    description: 'Resolves domain names to IPs. First hop of every request.',
  },

  /* ---- Routing ---- */
  {
    id: 'lb-l7-nginx',
    type: 'loadBalancer',
    name: 'Load Balancer (L7)',
    icon: '⚖️',
    category: 'routing',
    baseLatency: 2,
    capacity: 50_000,
    costPerMonth: 100,
    availability: 0.9999,
    failureRate: 0.0001,
    description: 'Distributes traffic across app servers. L7 = smart (path/host based) routing.',
  },
  {
    id: 'lb-l4',
    type: 'loadBalancer',
    name: 'Load Balancer (L4)',
    icon: '🔀',
    category: 'routing',
    baseLatency: 1,
    capacity: 100_000,
    costPerMonth: 80,
    availability: 0.9999,
    failureRate: 0.0001,
    description: 'Fast connection-level load balancing. Cheaper, less smart than L7.',
  },
  {
    id: 'gateway-api',
    type: 'gateway',
    name: 'API Gateway',
    icon: '🚪',
    category: 'routing',
    baseLatency: 8,
    capacity: 40_000,
    costPerMonth: 150,
    availability: 0.9999,
    failureRate: 0.0001,
    description: 'Auth, rate limiting, request routing. Single entry point for clients.',
  },

  /* ---- Compute ---- */
  {
    id: 'app-node',
    type: 'appServer',
    name: 'App Server (Node)',
    icon: '🖥️',
    category: 'compute',
    baseLatency: 50,
    capacity: 5_000,
    costPerMonth: 150,
    availability: 0.999,
    failureRate: 0.001,
    description: 'Runs your application logic. Scale horizontally by adding replicas.',
  },
  {
    id: 'app-python',
    type: 'appServer',
    name: 'App Server (Python)',
    icon: '🐍',
    category: 'compute',
    baseLatency: 60,
    capacity: 4_000,
    costPerMonth: 140,
    availability: 0.999,
    failureRate: 0.001,
    description: 'Application server. Slower per-request but great for data work.',
  },

  /* ---- Data ---- */
  {
    id: 'db-postgres',
    type: 'dbSQL',
    name: 'PostgreSQL',
    icon: '🐘',
    category: 'data',
    baseLatency: 10,
    capacity: 10_000,
    costPerMonth: 500,
    availability: 0.999,
    failureRate: 0.002,
    description: 'Relational DB with ACID guarantees. Strong consistency, structured data.',
  },
  {
    id: 'db-postgres-replica',
    type: 'dbSQL',
    name: 'Postgres Read Replica',
    icon: '📋',
    category: 'data',
    baseLatency: 12,
    capacity: 15_000,
    costPerMonth: 400,
    availability: 0.999,
    failureRate: 0.002,
    description: 'Offloads reads from the primary. Improves read throughput & resilience.',
  },
  {
    id: 'db-mongo',
    type: 'dbNoSQL',
    name: 'MongoDB',
    icon: '🍃',
    category: 'data',
    baseLatency: 8,
    capacity: 20_000,
    costPerMonth: 450,
    availability: 0.999,
    failureRate: 0.002,
    description: 'Document store. Flexible schema, easy horizontal scaling.',
  },
  {
    id: 'db-cassandra',
    type: 'dbNoSQL',
    name: 'Cassandra',
    icon: '🌀',
    category: 'data',
    baseLatency: 5,
    capacity: 50_000,
    costPerMonth: 600,
    availability: 0.9995,
    failureRate: 0.0005,
    description: 'Wide-column store built for massive write throughput & multi-region.',
  },
  {
    id: 'redis',
    type: 'cache',
    name: 'Redis Cache',
    icon: '⚡',
    category: 'data',
    baseLatency: 1,
    capacity: 80_000,
    costPerMonth: 120,
    availability: 0.999,
    failureRate: 0.001,
    description: 'In-memory key-value store. Blazing fast reads. Use to cache hot data.',
    props: { cacheHitRatio: 0.85 },
  },
  {
    id: 's3',
    type: 'objectStorage',
    name: 'Object Storage (S3)',
    icon: '🗄️',
    category: 'data',
    baseLatency: 30,
    capacity: 60_000,
    costPerMonth: 100,
    availability: 0.9999,
    failureRate: 0.0001,
    description: 'Durable blob storage for files, images, backups. Effectively infinite scale.',
  },

  /* ---- Messaging ---- */
  {
    id: 'kafka',
    type: 'queue',
    name: 'Kafka',
    icon: '📨',
    category: 'messaging',
    baseLatency: 5,
    capacity: 100_000,
    costPerMonth: 300,
    availability: 0.9999,
    failureRate: 0.0001,
    description: 'Distributed event log. Decouples producers from consumers, buffers bursts.',
  },
  {
    id: 'rabbitmq',
    type: 'queue',
    name: 'RabbitMQ',
    icon: '🐰',
    category: 'messaging',
    baseLatency: 4,
    capacity: 40_000,
    costPerMonth: 180,
    availability: 0.999,
    failureRate: 0.001,
    description: 'Traditional message broker. Great for task queues & RPC patterns.',
  },
];

/** Quick lookup by id. */
export const COMPONENT_BY_ID: Record<string, ComponentDef> = Object.fromEntries(
  COMPONENTS.map((c) => [c.id, c]),
);
